### ISSUE TITLE
Corrupted ER-model screenshot with Safari 14 (maybe html2canvas related)

### ISSUE THREAD

**Issue by dotWee** [jschildgen/monster-park#2]
I've just finished going through the game and generated a certificate of completion, but it seems as something went wrong while html2canvas screenshot'ed my ER model.

Could be my Safari browser just had a hiccup, or the html2canvas dependency is buggy and something faulted. Yet checking the javascript console doesn't show any abnormalities.

### Debugging Details

- Certificate Id: `4bf2f92471`
- Browser User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15`

### Javascript Console

![Screenshot 2020-11-03 at 17 20 19](https://user-images.githubusercontent.com/8060356/98013214-5f219d00-1dfa-11eb-8c3c-69cd6830cbe9.png)

### Certificate Screenshot

![Screenshot 2020-11-03 at 17 45 09](https://user-images.githubusercontent.com/8060356/98014823-68ac0480-1dfc-11eb-932a-47cb1f53b5d1.png)

**Comment by dotWee** [comment]
Looks like updating the html2canvas update with commit 5f21dda doesn't seem to fix the issue, the generated certificate is still corrupted.  

But interestingly the diagram gets exactly cut off at the same position, which seems interesting.  

Also since Safari's javascript api differentiates massively in comparison to Chromium/Firefox, possibly html2canvas calls some buggy implemented apis? I'll check out the Safari Technical Preview later, If there's any difference I'll report back.  

Edit: Screenshots for reference

The drawn diagram:

![The drawn diagram](https://user-images.githubusercontent.com/8060356/107883744-fd8cc680-6ef0-11eb-901b-edffc5d8870a.png)

The generated certificate:

![The generated certificate](https://user-images.githubusercontent.com/8060356/107883750-0a111f00-6ef1-11eb-943e-25952842c478.png)

**Comment by jschildgen** [comment]
We recommend using Google Chrome or Chromium. Here, the certificate generation works best.
