### ISSUE TITLE
Ungenauigkeit bei Bezeichnern

### ISSUE THREAD

**Issue by pintman** [jschildgen/monster-park#3]
Es wird in einer Aufgabe nach "Spitznamen" [im Text](https://github.com/jschildgen/monster-park/blob/master/js/game.js#L390) gefragt, in der Lösung aber nur "spitzname" akzeptiert. Das ist häufig verwirrend. Ein andere Formulierung in der Aufgabe wäre schön.

**Comment by jschildgen** [comment]
Im Text steht "dass jeder Trainer eine Trainer-ID, einen Spitznamen und ein Geschlecht hat."
"Spitznamen" ist hier Akkusativ Singular. Wen oder was. Ins ER-Diagramm kommt dann also "Spitzname".
Ich werde diese Aufgabe aber zur besseren Verständlichkeit aber umformulieren.

**Comment by pintman** [comment]
Ich gebe dir recht. Dennoch ist dies ein typischer Stolperstein, über den viele meiner Schüler stolpern, ohne, dass hierbei ein Verständnis über die ER-Modellierung einher ginge. Danke für die Anpassung und die schnelle Reaktion. :)

**Comment by jschildgen** [comment]
Das ist gar nicht so einfach, den Akkusativ zu vermeiden. An anderen Stellen steht auch "Ein Monster hat einen Name**n**", "Ein Team hat einen Teamnamen".

Ich habe es nun so geändert:
"Male bitte auf, dass es Trainer geben. Jeder Trainer hat: Trainer-ID, Spitzname und ein Geschlecht."

Um im jeden Fall die neue Spielversion im Browser zu haben, kann es nötig sein, mit Strg+Umschalt+F5 einen Reload der Javascript-Dateien zu erzwingen.

**Comment by pintman** [comment]
Danke für die schnelle Umsetzung. :)

Jetzt ist der erste Satz etwas ungelenkt. Vermutlich besser 

"Male bitte auf, dass es Trainer geben kann." oder
"Male bitte auf, dass es Trainer gibt." 

statt 

"Male bitte auf, dass es Trainer geben."

**Comment by jschildgen** [comment]
Danke, ist gefixt.
